### ISSUE TITLE
Failed to execute script

### ISSUE THREAD

**Issue by stickerx** [KingHacker9000/Claim-Free-Games#3]
DevTools listening on ws://127.0.0.1:64042/devtools/browser/b1018ee8-b335-45f5-a2b6-4a762682d1aa
Traceback (most recent call last):
  File "Buy_Free_Games.py", line 21, in <module>
    driver = webdriver.Chrome(r"chromedriver.exe")
  File "lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 76, in __init__
  File "lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
  File "lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
  File "lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
  File "lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 83

[3984] Failed to execute script Buy_Free_Games

Press Enter or Esc to close console...

**Comment by tigercoding56** [comment]
update your chrome-driver package ?

**Comment by tigercoding56** [comment]
also why are you using the linux version on a windows install ?
just use linux natively   it is easier than LTT makes it seem 
(or run it on a raspberry pi or similar )
